config/routes.rb
Rails.application.routes.draw do
  

  post '/establecimientos/ver_documento'
  delete '/establecimientos/borrar_foto'
  delete '/establecimientos/borrar_documento'
  resources :establecimientos  
  post '/establecimientos/guardar_foto'
  post '/establecimientos/guardar_documento'
  get 'home/index'

  devise_for :users

  root 'establecimientos#index'

end

app/models/documento.rb
class Documento < ActiveRecord::Base
	has_paper_trail
	belongs_to :establecimiento

	has_attached_file :archivo, styles: {}, 
		path: '/home/ruby/archivos/:id.:extension', 
		url:'/home/ruby/archivos/:id.:extension'


  	validates_attachment :archivo, presence: true, 
  	content_type: { content_type: "application/pdf" }

end

app/models/establecimiento.rb
class Establecimiento < ActiveRecord::Base
	has_paper_trail
	has_many :fotos
	has_many :documentos
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  has_paper_trail

  has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100"}, default_url: "/images/:style/missing.png"

  validates_attachment :foto, presence: true, content_type: { content_type: "image/jpeg" }

	belongs_to :establecimiento

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_paper_trail

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :set_paper_trail_whodunnit
  
end

app/controllers/establecimientos_controller.rb
class EstablecimientosController < ApplicationController
  before_action :set_establecimiento, only: [:show, :edit, :update, :destroy]

  # GET /establecimientos
  # GET /establecimientos.json
  def index
    @establecimientos = Establecimiento.all
  end

  # GET /establecimientos/1
  # GET /establecimientos/1.json
  def show
    @foto = Foto.new
    @foto.establecimiento_id = @establecimiento.id    
    @documento = Documento.new
    @documento.establecimiento_id = @establecimiento.id
  end

  def guardar_foto
    begin
      @establecimiento = Establecimiento.find(params[:foto][:establecimiento_id])
      foto = Foto.create!(params.require(:foto).permit(:establecimiento_id, :foto))
      flash[:notice] = 'Foto creada correctamente'
      
    rescue Exception => e
      flash[:alert] = 'Error al guardar: ' << e.message
    ensure
      redirect_to @establecimiento
    end    
  end

  def borrar_foto
    foto = Foto.find(params[:id])
    @establecimiento = foto.establecimiento
    if foto.destroy
      flash[:notice] = 'Eliminado correctamente'
    else
      flash[:alert] = 'Error al eliminar'
    end
    redirect_to @establecimiento
  end


  def guardar_documento
    begin
      @establecimiento = Establecimiento.find(params[:documento][:establecimiento_id])
      documento = Documento.create!(params.require(:documento).permit(:establecimiento_id, :archivo))
      flash[:notice] = 'Documento creado correctamente'
      
    rescue Exception => e
      flash[:alert] = 'Error al guardar: ' << e.message
    ensure
      redirect_to @establecimiento
    end    
  end

  def borrar_documento
    documento = Documento.find(params[:id])
    @establecimiento = documento.establecimiento
    if documento.destroy
      flash[:notice] = 'Eliminado correctamente'
    else
      flash[:alert] = 'Error al eliminar'
    end
    redirect_to @establecimiento
  end

  def ver_documento
    documento = Documento.find(params[:id])
    file = File.new(documento.archivo.path)
    send_file file, disposition: 'inline', type: 'application/pdf'
  end



  # GET /establecimientos/new
  def new
    @establecimiento = Establecimiento.new
  end

  # GET /establecimientos/1/edit
  def edit
  end

  # POST /establecimientos
  # POST /establecimientos.json
  def create
    @establecimiento = Establecimiento.new(establecimiento_params)

    respond_to do |format|
      if @establecimiento.save
        format.html { redirect_to @establecimiento, notice: 'Establecimiento was successfully created.' }
        format.json { render :show, status: :created, location: @establecimiento }
      else
        format.html { render :new }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /establecimientos/1
  # PATCH/PUT /establecimientos/1.json
  def update
    respond_to do |format|
      if @establecimiento.update(establecimiento_params)
        format.html { redirect_to @establecimiento, notice: 'Establecimiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @establecimiento }
      else
        format.html { render :edit }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /establecimientos/1
  # DELETE /establecimientos/1.json
  def destroy
    @establecimiento.destroy
    respond_to do |format|
      format.html { redirect_to establecimientos_url, notice: 'Establecimiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_establecimiento
      @establecimiento = Establecimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def establecimiento_params
      params.require(:establecimiento).permit(:nombre)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/establecimientos_helper.rb
module EstablecimientosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/establecimientos/_form.html.erb
<%= form_for(@establecimiento) do |f| %>
  <% if @establecimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@establecimiento.errors.count, "error") %> prohibited this establecimiento from being saved:</h2>

      <ul>
      <% @establecimiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/establecimientos/edit.html.erb
<h1>Editing Establecimiento</h1>

<%= render 'form' %>

<%= link_to 'Show', @establecimiento %> |
<%= link_to 'Back', establecimientos_path %>

app/views/establecimientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Establecimientos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @establecimientos.each do |establecimiento| %>
      <tr>
        <td><%= establecimiento.nombre %></td>
        <td><%= link_to 'Show', establecimiento %></td>
        <td><%= link_to 'Edit', edit_establecimiento_path(establecimiento) %></td>
        <td><%= link_to 'Destroy', establecimiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Establecimiento', new_establecimiento_path %>

app/views/establecimientos/new.html.erb
<h1>New Establecimiento</h1>

<%= render 'form' %>

<%= link_to 'Back', establecimientos_path %>

app/views/establecimientos/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Establecimiento</h1>
<p>
  <strong>Nombre:</strong>
  <%= @establecimiento.nombre %>
</p>


<h1>Documentos</h1>
<%= form_for @documento, url: '/establecimientos/guardar_documento', html: { multipart: true} do |f| %>

  <%= f.hidden_field :establecimiento_id %>
  <%= f.file_field :archivo%>
  <%= f.submit %>

<% end %>

<table class="table">
<thead>
	<th>documento_file_name</th>
	<th>documento_content_type</th>
	<th>documento_file_size</th>
	<th colspan="2">Acciones</th>
</thead>
<% @establecimiento.documentos.each do |f| %>
<tr>
	<td><%= f.archivo_file_name %></td>
	<td><%= f.archivo_content_type %></td>
	<td><%= f.archivo_file_size %></td>

<td>
	<%= form_tag '/establecimientos/ver_documento',{method: :post, target: '_blank'} do %>
	  <%= hidden_field_tag :id, f.id %>
      <%= submit_tag 'Descargar' %>
	<% end %>
</td>


	<td>
		<%= form_tag '/establecimientos/borrar_documento', method: :delete do %>
		  <%= hidden_field_tag :id, f.id %>
          <%= submit_tag 'Borrar', data: { confirm: "Estás seguro?"} %>
		<% end %>
	</td>

</tr>
<% end %>
</table>


<h1>Fotos</h1>
<%= form_for @foto, url: '/establecimientos/guardar_foto', html: { multipart: true} do |f| %>

  <%= f.hidden_field :establecimiento_id %>
  <%= f.file_field :foto%>
  <%= f.submit %>

<% end %>

<table class="table">
<thead>
	<th>Vista_previa</th>
	<th>foto_file_name</th>
	<th>foto_content_type</th>
	<th>foto_file_size</th>
	<th colspan="4">Acciones</th>
</thead>
<% @establecimiento.fotos.each do |f| %>
<tr>
	<td><%= image_tag f.foto.url(:thumb) %></td>
	<td><%= f.foto_file_name %></td>
	<td><%= f.foto_content_type %></td>
	<td><%= f.foto_file_size %></td>
	<td><%= link_to 'Ver thumb' , f.foto.url(:thumb), {target: '_blank'} %></td>
	<td><%= link_to 'Ver medium' , f.foto.url(:medium), {target: '_blank'} %></td>
	<td><%= link_to 'Ver original' , f.foto.url(:original), {target: '_blank'} %></td>
	<td>
		<%= form_tag '/establecimientos/borrar_foto', method: :delete do %>
		  <%= hidden_field_tag :id, f.id %>
          <%= submit_tag 'Borrar', data: { confirm: "Estás seguro?"} %>
		<% end %>
	</td>
</tr>
<% end %>
</table>






<%= link_to 'Edit', edit_establecimiento_path(@establecimiento) %> |
<%= link_to 'Back', establecimientos_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digitalizacion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Salir', destroy_user_session_url, method: :delete%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>